import type { Product } from "@/components/product-card";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Colors of Spring",
    category: "Casual Sneakers",
    price: 2990,
    image: [
      "/images/products/s1.png",
      "/images/products/s2.png",
      "/images/products/s3.png",
      "/images/products/s4.png",
      "/images/products/s5.png",
      "/images/products/s6.png",
    ],
    badge: "limited drop: 300x",
    description:
      "Some people aren't made to fit in, no matter how hard they try.",
  },
  {
    id: 2,
    name: "Postcards of Dhaka",
    category: "Casual Sneakers",
    price: 3100,
    image: [
      "/images/products/p1.png",
      "/images/products/p2.png",
      "/images/products/p3.png",
      "/images/products/p4.png",
      "/images/products/p5.png",
      "/images/products/p6.png",
    ],
    badge: "limited drop: 150x",
    description: "This design isn't just postcards. It's a perspective.",
  },
  // {
  //   id: 3,
  //   name: "Urban Classic",
  //   category: "Lifestyle",
  //   price: 4200,
  //   image: "/images/products/3-urban-classic.avif",
  // },
  // {
  //   id: 4,
  //   name: "Velocity Pro",
  //   category: "Sports",
  //   price: 6200,
  //   originalPrice: 7500,
  //   image: "/images/products/4-velocity-pro.avif",
  //   badge: "sale",
  // },
  // {
  //   id: 5,
  //   name: "Street Runner",
  //   category: "Lifestyle Sneakers",
  //   price: 4500,
  //   image: "/images/products/5-street-runner.avif",
  //   badge: "bestseller",
  // },
  // {
  //   id: 6,
  //   name: "Urban Flex",
  //   category: "Casual Sneakers",
  //   price: 3900,
  //   image: "/images/products/6-urban-flex.avif",
  //   badge: "bestseller",
  // },
  // {
  //   id: 7,
  //   name: "Court Classic",
  //   category: "Everyday Sneakers",
  //   price: 5200,
  //   image: "/images/products/7-court-classic.avif",
  // },
  // {
  //   id: 8,
  //   name: "Motion X",
  //   category: "Sports Sneakers",
  //   price: 5800,
  //   image: "/images/products/8-motion-x.avif",
  //   originalPrice: 6800,
  //   badge: "sale",
  // },
];
