import type { Product } from "@/components/product-card";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Air Runner",
    category: "Running Sneakers",
    price: 5500,
    image: "/images/products/1-air-runner.avif",
    badge: "new",
  },
  {
    id: 2,
    name: "Street Force",
    category: "Casual Sneakers",
    price: 4800,
    image: "/images/products/2-street-force.avif",
    badge: "bestseller",
  },
  {
    id: 3,
    name: "Urban Classic",
    category: "Lifestyle",
    price: 4200,
    image: "/images/products/3-urban-classic.avif",
  },
  {
    id: 4,
    name: "Velocity Pro",
    category: "Sports",
    price: 6200,
    originalPrice: 7500,
    image: "/images/products/4-velocity-pro.avif",
    badge: "sale",
  },
  {
    id: 5,
    name: "Street Runner",
    category: "Lifestyle Sneakers",
    price: 4500,
    image: "/images/products/5-street-runner.avif",
    badge: "bestseller",
  },
  {
    id: 6,
    name: "Urban Flex",
    category: "Casual Sneakers",
    price: 3900,
    image: "/images/products/6-urban-flex.avif",
    badge: "bestseller",
  },
  {
    id: 7,
    name: "Court Classic",
    category: "Everyday Sneakers",
    price: 5200,
    image: "/images/products/7-court-classic.avif",
  },
  {
    id: 8,
    name: "Motion X",
    category: "Sports Sneakers",
    price: 5800,
    image: "/images/products/8-motion-x.avif",
    originalPrice: 6800,
    badge: "sale",
  },
];
