import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Footer } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  metadataBase: new URL("https://monetwear.com/homepage"),
  title: {
    default: "Monet",
    template: "%s | Monet",
  },
  description: "It isn't for everyone - and we never wanted it to be.",
  authors: [{ name: "Monet" }],
  creator: "Monet",
  publisher: "Monet",
  openGraph: {
    title: "Monet",
    description: "It isn't for everyone - and we never wanted it to be.",
    siteName: "Monet",
    url: "https://monetwear.com/homepage",
    images: [
      {
        url: "/images/monet-logo-w-on-b.png",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en-US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
  },
  icons: {
    icon: "/images/monet-logo-w-on-trans.png",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
