import type { Metadata } from "next";
import { Geist, Geist_Mono, Comfortaa } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Footer } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: {
    default: "Monet",
    template: "%s | Monet",
  },
  description:
    "A new way to move is almost here. Discover everyday sneakers designed to move differently.",
  openGraph: {
    title: "Monet",
    description:
      "A new way to move is almost here. Discover everyday sneakers designed to move differently.",
    url: "https://monetwear.com/",
    siteName: "Monet",
    // images: [
    //   {
    //     url: "https://monetwear.com/og.png",
    //     width: 1200,
    //     height: 630,
    //   },
    // ],
    locale: "en-US",
    type: "website",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${comfortaa.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
